[workspace]
members = ["romm-api", "romm-cli", "romm-tui"]
resolver = "2"

[workspace.package]
edition = "2021"
repository = "https://github.com/patricksmill/romm-cli"
license = "MIT"

[workspace.dependencies]
romm-api = { path = "romm-api", version = "0.40" }
romm-tui = { path = "romm-tui", version = "0.40" }

[profile.release]
strip = true
