[workspace]
members = ["romm-api", "romm-cli", "romm-tui"]
resolver = "2"

[workspace.package]
edition = "2021"
repository = "https://github.com/patricksmill/romm-cli"
license = "MIT"

[workspace.dependencies]
romm-api = { path = "romm-api", version = "1.2" }

[profile.release]
strip = true
lto = true
codegen-units = 1
opt-level = "s"
panic = "abort"
